Document: pmaccoord
Title: Debian pmaccoord Manual
Author: <insert document author here>
Abstract: This manual describes what pmaccoord is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pmaccoord/pmaccoord.sgml.gz

Format: postscript
Files: /usr/share/doc/pmaccoord/pmaccoord.ps.gz

Format: text
Files: /usr/share/doc/pmaccoord/pmaccoord.text.gz

Format: HTML
Index: /usr/share/doc/pmaccoord/html/index.html
Files: /usr/share/doc/pmaccoord/html/*.html
