/* This file was automatically generated on Fri 03 Aug 2012 11:51:44 BST from
 * source: /dls_sw/prod/R3.14.11/support/pmacCoord/1-11/etc/makeIocs/CS3jack.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

