TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
DB += accel_dcm.template
DB += IDT_sagital_dcm.template
DB += aperture_slits.template
DB += bender.template
DB += B22_optics_box.template
DB += blade_slits.template
DB += gap_and_centre_slits.template
DB += flexure_slits.template
DB += 2jack.template
DB += 3jack.template
DB += 3jack_mirror.template
DB += qcm.template
DB += motor_in_cs.template
DB += pmacVariableWriteSync.template
DB += zform.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

