TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
#DB += accel_dcm.template
#DB += IDT_sagital_dcm.template
#DB += aperture_slits.template
#DB += bender.template
#DB += B22_optics_box.template
#DB += blade_slits.template
#DB += gap_and_centre_slits.template
#DB += flexure_slits.template
#DB += 2jack.template
#DB += 3jack.template
#DB += 3jack_mirror.template
#DB += qcm.template
#DB += motor_in_cs.template
#DB += pmacVariableWriteSync.template
#DB += zform.template

DB += accel_dcm.vdb
DB += IDT_sagital_dcm.vdb
DB += aperture_slits.vdb
DB += bender.vdb
DB += B22_optics_box.vdb
DB += blade_slits.vdb
DB += gap_and_centre_slits.vdb
DB += flexure_slits.vdb
DB += 2jack.vdb
DB += 3jack.vdb
DB += 3jack_mirror.vdb
DB += qcm.vdb
DB += motor_in_cs.template
DB += pmacVariableWriteSync.vdb
DB += zform.vdb

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

